
/**
 * Represents a single entry in the PhoneBook (Voter List).
 * Matches the 'phoneBook' table in your schema.
 */
export interface Contact {
  id: string;           // UUID
  firstName: string;
  lastName: string;
  phoneNumber: string;
  age: number | null;   // Nullable in case age is unknown
  party: 'Democrat' | 'Republican' | 'Independent' | 'Green' | 'Libertarian' | string; 
  worknotes?: string;   // UUID reference to workNotes table (optional in frontend view)
}

/**
 * Represents a record of a call or interaction.
 * Matches the 'workNotes' and 'call' tables in your schema.
 */
export interface CallHistoryItem {
  id: string;           // UUID
  date: string;         // ISO Timestamp
  duration: number;     // Seconds
  completed: boolean;   // Was the call completed?
  note: string;         // Short summary (e.g., "Left Voicemail")
  transcript?: string;  // Detailed text or transcription
  author: string;       // Name of the volunteer/user who made the call
}

/**
 * Props for the AddContactForm component
 */
export interface AddContactFormProps {
  isOpen: boolean;
  onCancel: () => void;
  onSubmit: (contact: Omit<Contact, 'id'>) => void; // ID is generated by backend usually
}

/**
 * Props for the ContactsTable component
 */
export interface ContactsTableProps {
  contacts: Contact[];
  onViewHistory: (contact: Contact) => void;
}

/**
 * Props for the CallHistoryModal component
 */
export interface CallHistoryModalProps {
  opened: boolean;
  onClose: () => void;
  contact: Contact | null; // Null if no contact is selected
}